#Heroku Kafka data

kafka:
  broker: "kafka+ssl://ec2-18-208-61-56.compute-1.amazonaws.com:9096,kafka+ssl://ec2-34-235-216-30.compute-1.amazonaws.com:9096,kafka+ssl://ec2-18-204-47-99.compute-1.amazonaws.com:9096,kafka+ssl://ec2-18-233-211-98.compute-1.amazonaws.com:9096,kafka+ssl://ec2-18-233-140-74.compute-1.amazonaws.com:9096,kafka+ssl://ec2-34-203-24-91.compute-1.amazonaws.com:9096,kafka+ssl://ec2-52-204-144-208.compute-1.amazonaws.com:9096,kafka+ssl://ec2-34-224-229-106.compute-1.amazonaws.com:9096"
  #To get the Broker URL variable, run the command 'heroku config:get KAFKA_URL --app replaceWithYourHerokuAppName'
  topic: "connecticut-1118.test01"
  #Get the heroku kafka topic list by running the command 'heroku kafka:topics --app replaceWithYourHerokuAppName'
  consumerGroup: "connecticut-1118.test-consumer"
  #If you add a consumer, you need to create a consumer group, to do it, run the command 'heroku kafka:consumer-groups:create consumerGroupName --app replaceWithYourHerokuAppName'
  keystore:
    filepath: "kafka.client.keystore.jks"
    type: "JKS"
    password: "mule123"
  truststore:
    filepath: "kafka.client.truststore.jks"
    type: "JKS"
    password: "mule123"
  #Play with the paramenter values below and add others. If you add another one, remember to add the variable on the producer config in global.xml (global elements tab)
  param:
    batchsize: "50000"
    requesttimeoutms: "60000"
    lingerms: "0"
    ack: "1"

#JSON File to be loaded, located in scr/main/resourses.
file:
  name: "1000.json"
